server:
  port: 8761
spring:
  application:
    name: spring-hystrix-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#---
#server: 
#  port: 8762
#spring: 
#  application:
#    name: first-114
#  profiles: slaveB
#eureka: 
#  client: 
#    serviceUrl: 
#      defaultZone: http://slave1:8761/eureka/